### PR TITLE
Tiger abbrev

### PR DESCRIPTION
**Pull request by darrell**
Two commits. 

1) Bump version since we're changing behavior, 

2) the actual commit to add ambiguity preserving for directions.

Also, like how I mangled thesaurus?

### CODE REVIEW

**Comment by pramsey** [comment]
For completeness (this is where I use my Yoda voice) add a version upgrade script you must. Mmm.

That is, add a addressing_dictionary--1.0--1.1.sql file that does the incremental changes necessary to transition from 1.0 to 1.1. This enables the ALTER extension UPDATE TO functionality.

**Comment by darrell** [comment]
Pull request updated.

**Comment by pramsey** [comment]
You don't need to keep the old version around, just have a path from old to new.

**Comment by darrell** [comment]
picky, picky! 1.0 now removed.

**Pull request merged**
